StartupEvents.registry('item', e => {
    e.create('alien_shard').displayName('Чужеродный осколок')
    e.create('arkanium_nugget').displayName('Арканиумовый самородок')
    e.create('azurit_nugget').displayName('Азуритовый самородок')
    e.create('azurit_asid').displayName('Азуритовая кислота')
    e.create('azurit_shard').displayName('Азуритовый осколок')
    e.create('ceramic_catalist').displayName('Керамический катализатор')
    e.create('clay_catalist').displayName('Глиняный катализатор')
    e.create('construction_alloy').displayName('Конструкционный сплав')
    e.create('dangerous_dust').displayName('Опасная пыль')
    e.create('dangerous_shard').displayName('Токсичный осколок')
    e.create('especially_rare_shard').displayName('Особо редкий осколок')
    e.create('fulled_particle_trap').displayName('Заполненная ловушка частиц')
    e.create('fulled_processing_core').displayName('Заполненное ядро обработки')
    e.create('fulled_void_processing_core').displayName('Заполненное пустотное обрабатывающее ядро')
    e.create('hexium_ingot').displayName('Слиток хексия')
    e.create('hexium_nugget').displayName('Хексиевый самородок')
    e.create('indium_alloy').displayName('Сплав ИНДИЙ')
    e.create('indium_ingot').displayName('Слиток индия')
    e.create('indium_nugget').displayName('Индиевый самородок')
    e.create('iridium_ingot').displayName('Слиток иридия')
    e.create('iridium_nugget').displayName('Иридиевый самородок')
    e.create('karasium_asid').displayName('Каразиумовая кислота')
    e.create('karasium_nugget').displayName('Казиумовый самородок')
    e.create('lukium_nugget').displayName('Лукиевый самородок')
    e.create('nanits').displayName('Нариты')
    e.create('nanocarbon_alloy').displayName('Наноуглеродный сплав')
    e.create('neodymium_ingot').displayName('Слиток неодима')
    e.create('neodymium_nugget').displayName('Неодимовый самородок')
    e.create('palladium_ingot').displayName('Слиток палладия')
    e.create('palladium_nugget').displayName('Палладиевый самородок')
    e.create('particle_trap').displayName('Ловушка частиц')
    e.create('phase_filter').displayName('Фазовый фильтр')
    e.create('platinum_catalist').displayName('Платиновый катализатор')
    e.create('platinum_ingot').displayName('Слиток платины')
    e.create('platinum_nugget').displayName('Платиновый самородок')
    e.create('polluted_ceramic_catalist').displayName('Загрязнённый керамический катализатор')
    e.create('polluted_clay_catalist').displayName('Загрязнённый глиняный катализатор')
    e.create('polluted_phase_filter').displayName('Загрязнённый фазовый фильтр')
    e.create('polluted_platinum_catalist').displayName('Загрязнённый платиновый катализатор')
    e.create('polluted_rare_earth_catalist').displayName('Загрязнённый редкоземельный катализатор')
    e.create('processing_core').displayName('Ядро обработки')
    e.create('rare_earth').displayName('Редкая земля')
    e.create('rare_earth_catalist').displayName('Редкоземельный катализатор')
    e.create('rit_alloy').displayName('RIT сплав')
    e.create('rodium_ingot').displayName('Слиток родия')
    e.create('rodium_nugget').displayName('Родиевый самородок')
    e.create('space_dust').displayName('космическая пыль')
    e.create('timeles_neodymium_ingot').displayName('Вневременной неодим')
    e.create('titanium_alloy').displayName('Титановый сплав')
    e.create('titanium_ingot').displayName('Слиток титана')
    e.create('titanium_nugget').displayName('Титановый самородок')
    e.create('tungsten_nugget').displayName('Вольфрамовый самородок')
    e.create('tungsten_steel').displayName('Вольфрамовая сталь')
    e.create('tus_arkanium_cristall').displayName('Темпоральнонестабильный кристалл аркания')
    e.create('tus_hexium_cristall').displayName('Темпоральнонестабильный кристалл хексиума')
    e.create('tus_karazium_cristall').displayName('Темпоральнонестабильный кристалл каразия')
    e.create('tus_lukium_cristall').displayName('Темпоральнонестабильный кристалл лукия')
    e.create('tus_zalium_cristall').displayName('Темпоральнонестабильный кристалл залия')
    e.create('void_processing_core').displayName('Пустотное ядро обработки')
    e.create('zalium_nugget').displayName('Залиевый самородок')
    e.create('stable_void_dust').displayName('Стабильная пустоная пыль')
    e.create('phase_matter').displayName('Фазовая материя')
    e.create('infinity_shard').displayName('Осколок бесконечности')
    e.create('matter_fiber').displayName('Ткань материи')
})
//e.create('').displayName('')
StartupEvents.registry('item', e => {
    e.create('st1_n').displayName('Лавоочищенный незерит').texture('kubejs:item/st1')
    e.create('st2_n').displayName('Травлёный незерит').texture('kubejs:item/st2')
    e.create('st3_n').displayName('Каталитически очищенный незерит').texture('kubejs:item/st3')
    e.create('st4_n').displayName('Фторированный незерит').texture('kubejs:item/st4')
    e.create('st5_n').displayName('Азурированный незерит').texture('kubejs:item/st5')
    e.create('st6_n').displayName('Термоядерно рафинированный незерит').texture('kubejs:item/st6')
    e.create('st7_n').displayName('Каразиево очищенный незерит').texture('kubejs:item/st7')
    e.create('st8_n').displayName('Пустотно очищенный незерит').texture('kubejs:item/st8')
    e.create('st9_n').displayName('Фазово очищенный незерит').texture('kubejs:item/st9')
})

StartupEvents.registry('item', e => {
    e.create('st1_a').displayName('Лавоочищенная чужеродная руда').texture('kubejs:item/st1')
    e.create('st2_a').displayName('Травлёная чужеродная руда').texture('kubejs:item/st2')
    e.create('st3_a').displayName('Каталитически очищенная чужеродная руда').texture('kubejs:item/st3')
    e.create('st4_a').displayName('Фторированная чужеродная руда').texture('kubejs:item/st4')
    e.create('st5_a').displayName('Азурированная чужеродная руда').texture('kubejs:item/st5')
    e.create('st6_a').displayName('Термоядерно рафинированная чужеродная руда').texture('kubejs:item/st6')
    e.create('st7_a').displayName('Каразиево очищенная чужеродная руда').texture('kubejs:item/st7')
    e.create('st8_a').displayName('Пустотно очищенная чужеродная руда').texture('kubejs:item/st8')
    e.create('st9_a').displayName('Фазово очищенная чужеродная руда').texture('kubejs:item/st9')
})

StartupEvents.registry('item', e => {
    e.create('st1_u').displayName('Лавоочищенный уран').texture('kubejs:item/st1')
    e.create('st2_u').displayName('Травлёный уран').texture('kubejs:item/st2')
    e.create('st3_u').displayName('Каталитически очищенный уран').texture('kubejs:item/st3')
    e.create('st4_u').displayName('Фторированный уран').texture('kubejs:item/st4')
    e.create('st5_u').displayName('Азурированный уран').texture('kubejs:item/st5')
    e.create('st6_u').displayName('Термоядерно рафинированный уран').texture('kubejs:item/st6')
    e.create('st7_u').displayName('Каразиево очищенный уран').texture('kubejs:item/st7')
    e.create('st8_u').displayName('Пустотно очищенный уран').texture('kubejs:item/st8')
    e.create('st9_u').displayName('Фазово очищенный уран').texture('kubejs:item/st9')
})